version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY:-}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
      - OCTANE_SERVER=frankenphp
      - SERVER_NAME=:8080
    volumes:
      - ./storage:/app/storage
      - ./database:/app/database
    command: >
      sh -c "
        php artisan key:generate --ansi &&
        php artisan migrate --force &&
        php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8080
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/frankenphp-info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加数据库服务
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    profiles:
      - mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - redis

volumes:
  mysql_data:
  redis_data: 